flowchart LR
    Follower -->|超时参与选举| Candidate
    Witness -->|超时参与投票| Candidate
    Follower  --- |心跳|Leader
    Leader --> |转移让出权限|Witness
    Candidate --> |超时重新选举| Candidate
    Candidate --> |收到大多数投票成为|Leader
    Leader --> |发现更高的term|Follower
    Candidate --> |发现新的term<br>发现新的leader|Follower
    Leader --- |读写扩散|Learner
    Follower --- |读写扩散|Learner
    Learner --- |读写扩散|Learner
    Learner <--> |角色转换|Follower